#!/bin/bash
image=$1
container_name=$2
filename=$(basename $image)

container_img=${filename}-${container_name}.img

mkdir -p /tmp/images
flash -n ${container_name} --output /tmp/images/${container_img} ${image}
docker run --rm --privileged=true -v /tmp/images:/usr/rpi/images duquesnay/prepare-hypriot-qemu images/${container_img} 6G
echo /tmp/images/${container_img}